name: Debug Workflow Trigger

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print event name
        run: echo "Event Trigger:${{ github.event_name }}"

      - name: Print ref and branch
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Print full event payload
        run: echo "${{ toJson(github) }}"
